# Generated starter migration
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name='Category', fields=[('id',models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('name',models.CharField(max_length=120)),('slug',models.SlugField(unique=True)),('image_label',models.CharField(blank=True, help_text='Text shown on demo category image', max_length=40))], options={'verbose_name_plural':'Categories'}),
        migrations.CreateModel(name='Order', fields=[('id',models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('full_name',models.CharField(max_length=160)),('email',models.EmailField(max_length=254)),('phone',models.CharField(blank=True, max_length=40)),('address',models.TextField()),('city',models.CharField(max_length=100)),('postcode',models.CharField(max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('status',models.CharField(choices=[('new','New'),('paid','Paid'),('shipped','Shipped'),('cancelled','Cancelled')], default='new', max_length=20)),('total',models.DecimalField(decimal_places=2, default=0, max_digits=10))]),
        migrations.CreateModel(name='Product', fields=[('id',models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('name',models.CharField(max_length=220)),('slug',models.SlugField(unique=True)),('brand',models.CharField(blank=True, max_length=120)),('description',models.TextField(blank=True)),('base_price',models.DecimalField(decimal_places=2, max_digits=10)),('image',models.ImageField(blank=True, null=True, upload_to='products/')),('colour',models.CharField(blank=True, max_length=80)),('is_featured',models.BooleanField(default=False)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('category',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category'))], options={'ordering':['-created_at']}),
        migrations.CreateModel(name='ProductVariant', fields=[('id',models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('size',models.CharField(default='One Size', max_length=50)),('price',models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),('stock',models.PositiveIntegerField(default=0)),('sku',models.CharField(blank=True, max_length=80)),('product',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product'))], options={'unique_together':{('product','size')}}),
        migrations.CreateModel(name='OrderItem', fields=[('id',models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('quantity',models.PositiveIntegerField(default=1)),('price',models.DecimalField(decimal_places=2, max_digits=10)),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),('variant',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.productvariant'))]),
    ]
